name: malarify
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.18.0
  flutter_animate: ^4.2.0+1
  font_awesome_flutter: ^10.5.0
  flutter_riverpod: ^2.3.10
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^10.1.2
  iconly: ^1.0.1
  lottie: ^2.6.0
  image_picker: ^1.0.3
  path_provider: ^2.1.0
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  page_transition: ^2.0.9
  flutter_localization: ^0.1.13
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_auth: ^4.8.0
  firebase_core_platform_interface: ^4.5.1
  syncfusion_flutter_calendar: ^20.3.48
  syncfusion_localizations: ^20.3.48
  url_launcher: ^6.1.12
  mime: ^1.0.4
  form_validators:
    path: packages/form_validators
  firebase_auth_repository:
    path: packages/firebase_auth_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  very_good_analysis: ^5.0.0+1
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/AeonikTRIAL-Light.otf
          weight: 400
        - asset: assets/fonts/AeonikTRIAL-Regular.otf
          weight: 500


