// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOop1FsSR1qGirdh6jvGCvaK2sUhvFX7I',
    appId: '1:1056581796930:web:e1db45912ca43acf5119db',
    messagingSenderId: '1056581796930',
    projectId: 'malarify-f346a',
    authDomain: 'malarify-f346a.firebaseapp.com',
    databaseURL: 'https://malarify-f346a-default-rtdb.firebaseio.com',
    storageBucket: 'malarify-f346a.appspot.com',
    measurementId: 'G-7B8RDD4RQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwvu1dduaWUYldgaQG3FCG-tWVR_BoOCo',
    appId: '1:1056581796930:android:064f873f2640f5c45119db',
    messagingSenderId: '1056581796930',
    projectId: 'malarify-f346a',
    databaseURL: 'https://malarify-f346a-default-rtdb.firebaseio.com',
    storageBucket: 'malarify-f346a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFgeeJRHPI1yaPB-GGqqcfga0VFduKic',
    appId: '1:1056581796930:ios:9f65a68eb36f20f65119db',
    messagingSenderId: '1056581796930',
    projectId: 'malarify-f346a',
    databaseURL: 'https://malarify-f346a-default-rtdb.firebaseio.com',
    storageBucket: 'malarify-f346a.appspot.com',
    iosClientId: '1056581796930-q8ekugkgovllv7manm2kronifskmt0a7.apps.googleusercontent.com',
    iosBundleId: 'com.frteiham.malarify',
  );
}
